--- #YAML:1.0
name: HTTP-CheckProxy
version: 0.1
author:
  - ~
abstract: Perl module for testing for open proxies
license: gpl
requires:
  LWP::UserAgent: 2.024
provides:
  HTTP::CheckProxy:
    file: lib/HTTP/CheckProxy.pm
    version: 0.1
generated_by: Module::Build version 0.24
